import { ArrowUpRight, Star, Quote } from 'lucide-react';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
const reviews = [['Natalia Grondys','Zawdzięczam Pani Monice tak wiele. To wyjątkowo zaangażowana specjalistka…','NG'],['Ola Dubiak','Z całego serca polecam Panią Monikę za niezwykle profesjonalne i pełne empatii przygotowanie naszego dziecka do frenotomii…','OD'],['Marta Barczyk','Bardzo duża wiedza, również od strony medycznej, dzięki czemu otrzymaliśmy pomoc w wyborze akcesoriów wspomagających…','MB']];
export function Reviews() { return <section id="opinie" className="section bg-card"><div className="wrap scroll-reveal"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">Opinie pacjentów</p><h2 className="section-title">Zaufanie, które wiele znaczy</h2></div><p className="flex items-center gap-2 text-sm"><Star className="size-5 fill-gold text-gold"/><strong className="text-xl">4,8</strong><span className="text-muted-foreground">na podstawie 20 opinii w Google</span></p></div><div className="mt-9 grid gap-5 md:grid-cols-3">{reviews.map(([name,text,initials])=><article key={name} className="item-card flex flex-col p-7"><div className="flex justify-between"><div className="flex gap-1" aria-label="5 gwiazdek">{Array.from({length:5},(_,i)=><Star key={i} className="size-3.5 fill-gold text-gold"/>)}</div><Quote className="size-5 text-gold/60"/></div><blockquote className="mt-6 flex-1 text-sm leading-relaxed">„{text}”</blockquote><div className="mt-7 flex items-center gap-3 border-t pt-5"><span className="flex size-9 items-center justify-center rounded-full bg-mint text-xs font-bold text-mint-foreground">{initials}</span><div><p className="text-sm font-bold">{name}</p><p className="text-xs text-muted-foreground">Opinia z Google</p></div></div></article>)}</div><div className="mt-7 text-center"><a href="https://www.google.com/maps/search/?api=1&query=Monika+Feder+Neurologopeda+Zalasewo" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 text-sm text-primary underline underline-offset-4">Zobacz wszystkie opinie w Google<ArrowUpRight className="size-4"/></a></div></div></section>; }
const faqs = [
 ['Kiedy zgłosić się z dzieckiem do neurologopedy?','Warto skonsultować trudności z ssaniem, gryzieniem, połykaniem, rozwojem mowy lub częste oddychanie przez usta. Konsultacja pomaga określić potrzeby dziecka i ustalić dalsze postępowanie. W razie nagłych trudności z oddychaniem lub połykaniem należy pilnie szukać pomocy medycznej.'],
 ['Czym różni się logopeda od neurologopedy?','Logopeda zajmuje się rozwojem i zaburzeniami mowy oraz komunikacji. Neurologopeda posiada dodatkowe przygotowanie do pracy z trudnościami związanymi z układem nerwowym, a także z zaburzeniami karmienia i połykania. Zakres wsparcia zależy od potrzeb pacjenta i kompetencji specjalisty.'],
 ['Czy terapia jest też dla dorosłych?','Tak. Wspieram dorosłych m.in. przy dysfagii oraz zaburzeniach mowy i komunikacji po urazach i incydentach neurologicznych. Plan terapii powstaje na podstawie indywidualnej oceny.'],
 ['Jak wygląda pierwsza wizyta?','Pierwsze spotkanie obejmuje wywiad, obserwację i ocenę funkcji istotnych dla zgłaszanych trudności. Warto zabrać dotychczasową dokumentację medyczną i wyniki badań. Podczas wizyty omawiamy wnioski i możliwe dalsze kroki.'],
 ['Ile trwa terapia?','Nie ma jednego czasu terapii dla wszystkich. Zależy on od rodzaju trudności, potrzeb i możliwości pacjenta oraz przebiegu pracy. Cele i postępy są regularnie omawiane; nie można z góry obiecać konkretnego rezultatu ani terminu.'],
 ['Czy współpracuje Pani z ortodontą i fizjoterapeutą?','Tak, współpracuję z ortodontami i fizjoterapeutami. Gdy potrzeby pacjenta tego wymagają, wspólne podejście pomaga skoordynować zalecenia i zaplanować terapię, także w związku z frenotomią lub leczeniem ortodontycznym.'],
];
export function Faq() { return <section className="section"><div className="wrap grid gap-8 md:grid-cols-[1fr_1.5fr] md:gap-20 scroll-reveal"><div><p className="eyebrow">Warto wiedzieć</p><h2 className="section-title">Twoje pytania.<br/>Spokojne odpowiedzi.</h2><p className="section-copy text-sm">Masz inne pytanie? Porozmawiajmy – wspólnie ustalimy, od czego zacząć.</p><a href="tel:+48605846554" className="mt-6 block font-display text-2xl text-primary">605 846 554</a></div><Accordion type="single" collapsible>{faqs.map(([q,a],i)=><AccordionItem value={`faq-${i}`} key={q}><AccordionTrigger className="py-5 text-base hover:no-underline">{q}</AccordionTrigger><AccordionContent className="pr-6 text-sm leading-relaxed text-muted-foreground">{a}</AccordionContent></AccordionItem>)}</Accordion></div></section>; }
