import { Baby, Users, UserRound, ArrowUpRight, Award, Heart, MessageCircle, Smile, Speech, Utensils, ScanFace, Brain, Scissors, Milk, Hand, Waves, Zap, Activity, Sparkles, Phone, ClipboardCheck, ListChecks, TrendingUp } from 'lucide-react';
import { Button } from '@/components/ui/button';
const audiences = [
 {icon:Baby, tag:'DOBRY POCZĄTEK', title:'Niemowlęta i małe dzieci', text:'Wsparcie w trudnościach z karmieniem, przy nieprawidłowym napięciu mięśniowym oraz przed frenotomią i po zabiegu.'},
 {icon:Users, tag:'ROZWÓJ I KOMUNIKACJA', title:'Dzieci przedszkolne i szkolne', text:'Terapia opóźnionego rozwoju mowy, wad wymowy oraz wsparcie przy wadach zgryzu i nieprawidłowych nawykach.'},
 {icon:UserRound, tag:'KOMFORT NA CO DZIEŃ', title:'Dorośli', text:'Pomoc przy dysfagii, korowych zaburzeniach mowy oraz trudnościach z komunikacją po urazach i incydentach neurologicznych.'},
];
export function Audiences() { return <section className="section bg-background"><div className="wrap scroll-reveal"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="eyebrow">Dla kogo jest terapia</p><h2 className="section-title">Wsparcie na każdym<br/>etapie życia</h2></div><p className="max-w-sm text-sm text-muted-foreground md:pb-2">Każda historia jest inna. Wspólnie znajdziemy drogę dopasowaną do Twoich potrzeb lub potrzeb Twojego dziecka.</p></div><div className="mt-9 grid gap-5 md:grid-cols-3">{audiences.map(({icon:Icon,tag,title,text},i) => <article key={title} className={`item-card p-7 ${i===1 ? 'border-primary/30' : ''}`}><div className={`icon-tile ${i===1?'bg-mint text-mint-foreground':''}`}><Icon strokeWidth={1.5}/></div><p className="mt-6 text-[10px] font-bold tracking-[1.5px] text-primary">{tag}</p><h3 className="mt-2 font-display text-2xl leading-tight">{title}</h3><p className="mt-4 text-sm text-muted-foreground">{text}</p><a href="#oferta" className="mt-6 inline-flex items-center gap-2 text-xs font-bold text-primary">Poznaj zakres terapii<ArrowUpRight className="size-3.5"/></a></article>)}</div></div></section>; }
export function About() { return <section id="o-mnie" className="section bg-mint"><div className="wrap grid items-center gap-10 md:grid-cols-2 md:gap-20 scroll-reveal"><div className="relative"><div className="flex aspect-[5/4] items-center justify-center rounded-lg border border-gold/40 bg-card/60"><div className="text-center"><UserRound className="mx-auto size-20 text-primary/40" strokeWidth={.7}/><p className="mt-5 font-display text-2xl">Monika Feder</p><p className="mt-1 text-xs text-muted-foreground">Zdjęcie specjalistki wkrótce</p></div></div><div className="absolute -bottom-4 right-4 flex items-center gap-3 rounded-md border bg-card px-5 py-4 shadow-sm"><Award className="size-7 text-primary"/><div className="text-xs"><strong className="block">Orły Medycyny</strong><span className="text-muted-foreground">Laureat plebiscytu</span></div></div></div><div><p className="eyebrow">Poznajmy się</p><h2 className="section-title">Wiedza i doświadczenie.<br/><span className="text-primary">Przede wszystkim – uważność.</span></h2><p className="mt-6 text-muted-foreground">Nazywam się Monika Feder. Od ponad dziesięciu lat wspieram dzieci i dorosłych w budowaniu swobodnej komunikacji i poprawie funkcji karmienia oraz połykania.</p><p className="mt-4 text-sm text-muted-foreground">Patrzę na pacjenta holistycznie – nie tylko na pojedynczą trudność. Współpracuję z ortodontami i fizjoterapeutami, a terapię dopasowuję do indywidualnych potrzeb, możliwości i codzienności każdej osoby.</p><div className="mt-6 flex items-center gap-3 text-sm"><Heart className="size-5 text-primary" strokeWidth={1.5}/>Empatia, cierpliwość i partnerska współpraca.</div><Button asChild variant="link" className="mt-5 px-0"><a href="#kontakt">Porozmawiajmy o Twoich potrzebach<ArrowUpRight/></a></Button></div></div></section>; }
const services = [
 [Smile,'Terapia miofunkcjonalna','Praca nad funkcjami języka, warg, oddychaniem i połykaniem.'],[MessageCircle,'Terapia wad wymowy','Wsparcie prawidłowej artykulacji i wyrazistości mowy.'],[Speech,'Opóźniony rozwój mowy','Rozwijanie mowy i umiejętności komunikacyjnych dziecka.'],[Utensils,'Zaburzenia karmienia i dysfagia','Ocena oraz terapia trudności z jedzeniem i połykaniem.'],[ScanFace,'Wady zgryzu i nawyki oralne','Wsparcie terapii ortodontycznej i prawidłowych funkcji oralnych.'],[Brain,'Korowe zaburzenia mowy','Indywidualna terapia komunikacji przy zaburzeniach neurologicznych.'],[Scissors,'Wsparcie przy frenotomii','Przygotowanie do zabiegu i opieka terapeutyczna po nim.'],[Milk,'Dobór akcesoriów','Doradztwo w doborze smoczków, butelek i przyborów do jedzenia.'],
] as const;
export function Services() { return <section id="oferta" className="section bg-card"><div className="wrap scroll-reveal"><p className="eyebrow">Zakres usług</p><h2 className="section-title">Terapia dopasowana do Ciebie</h2><p className="section-copy">Od pierwszych trudności w karmieniu po wsparcie komunikacji w dorosłości.</p><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{services.map(([Icon,title,text]) => <article key={title} className="item-card p-6"><Icon className="size-7 text-primary" strokeWidth={1.4}/><h3 className="mt-5 text-base font-bold leading-snug">{title}</h3><p className="mt-3 text-sm text-muted-foreground">{text}</p></article>)}</div></div></section>; }
const methods = [[Hand,'Masaż twarzy i jamy ustnej','Praca manualna wspierająca sprawność mięśni i czucie.'],[Sparkles,'Stymulacja orofacjalna','Ukierunkowana praca w obrębie twarzy i aparatu mowy.'],[Waves,'Wibratory logopedyczne','Stymulacja z użyciem narzędzi dobranych do potrzeb pacjenta.'],[Zap,'Elektrostymulacja','Technika uzupełniająca, stosowana po ocenie wskazań.'],[Activity,'Kinesiotaping logopedyczny','Aplikacje taśm jako wsparcie indywidualnej terapii.'],[Smile,'Terapia miofunkcjonalna','Ćwiczenia funkcji języka, warg i prawidłowych wzorców.']] as const;
export function Methods() { return <section id="metody" className="section"><div className="wrap scroll-reveal"><div className="text-center"><p className="eyebrow justify-center">Metody i techniki</p><h2 className="section-title">Nowoczesne narzędzia.<br/>Indywidualne podejście.</h2><p className="section-copy mx-auto">Metody dobieram po konsultacji i ocenie potrzeb. Nie każda technika jest odpowiednia dla każdego pacjenta.</p></div><div className="mt-10 grid gap-x-10 gap-y-8 sm:grid-cols-2 lg:grid-cols-3">{methods.map(([Icon,title,text]) => <div key={title} className="flex gap-4"><div className="icon-tile shrink-0 bg-mint text-mint-foreground"><Icon strokeWidth={1.4}/></div><div><h3 className="font-bold">{title}</h3><p className="mt-2 text-sm text-muted-foreground">{text}</p></div></div>)}</div></div></section>; }
export function Process() { const steps = [[Phone,'Pierwsza rozmowa','Zadzwoń i ustal dogodny termin spotkania.'],[ClipboardCheck,'Konsultacja i diagnoza','Porozmawiamy o trudnościach i ocenimy potrzeby.'],[ListChecks,'Twój plan terapii','Ustalimy cele i dobierzemy metody pracy.'],[TrendingUp,'Terapia i postępy','Regularne spotkania, ćwiczenia w domu i kontrola postępów.']] as const; return <section className="section border-y bg-mint"><div className="wrap scroll-reveal"><p className="eyebrow">Jak wygląda współpraca</p><h2 className="section-title">Pierwszy krok? Po prostu rozmowa.</h2><div className="mt-10 grid gap-7 sm:grid-cols-2 lg:grid-cols-4">{steps.map(([Icon,title,text],i)=><div className="relative border-t border-primary/25 pt-6" key={title}><span className="text-xs font-bold text-primary">0{i+1}</span><Icon className="float-right size-6 text-mint-foreground" strokeWidth={1.5}/><h3 className="mt-4 font-display text-2xl">{title}</h3><p className="mt-3 text-sm text-muted-foreground">{text}</p></div>)}</div></div></section>; }
